name: firebase_conn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cloud_firestore: ^5.6.5
  equatable: ^2.0.7
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  extensions: 
    git: 
      url: https://github.com/4CROS2/string_extensions.git 
      ref: main
  rxdart: ^0.28.0
  intl: 0.19.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_code_metrics: null

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Questrial
      fonts:
        - asset: assets/fonts/questrial.ttf

